default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USER", "rails_user") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "exam_review_app_development") %>

test:
  <<: *default
  database: exam_review_app_test

production:
  <<: *default
  database: exam_review_app_production
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
